Rules:
  ElapsedTime:
    class: Phm\Jmmd\Rule\ElapsedTimeRule
    parameters:
      maxValue: 30000

  ForbiddenStatusCode:
    class: Phm\Jmmd\Rule\ForbiddenStatusCode

  ErrorStatusCode:
    class: Phm\Jmmd\Rule\ErrorStatusCode

  NotFoundStatusCode:
    class: Phm\Jmmd\Rule\NotFoundStatusCode